### ISSUE TITLE
Allow some mobs to not despawn

### ISSUE THREAD

**Issue by thepilotvoltage** [Nukkit-coders/MobPlugin#142]
### Info

This is:
- [ ] bug report
- [X ] feature request
- [ ] other

### Your issue / suggestion

Players on my server are reporting that their captured mobs are despawning and the next time they get on their server they are not there. It would be nice if there was an option to exempt certain mobs from despawning.
### Configuration
Link to debugpaste:
```
<!-- Run debugpaste command and put the link here -->
```
Config:
```
<!-- Put your config.yml contents here  -->
# config version, do not edit!
config-version: 11

entities:
  # how often the spawn task should run
  # in ticks, 20 ticks = 1 second
  # use 0 to disable entity spawning
  autospawn-ticks: 200
  # how often the despawn task should run
  # in ticks, 20 ticks = 1 second
  # use 0 to disable entity despawning
  despawn-ticks: 6000
  # do not spawn entities in these worlds
  worlds-spawning-disabled: "exampleworld1, exampleworld2"

# spawning limit settings
# per player, in 100 blocks range
autospawn:
  bat: 1
  blaze: 2
  chicken: 2
  cod: 2
  cow: 2
  creeper: 2
  dolphin: 1
  donkey: 1
  enderman: 1
  ghast: 2
  husk: 2
  horse: 2
  magmacube: 2
  mooshroom: 2
  ocelot: 2
  parrot: 1
  pig: 2
  polarbear: 2
  pufferfish: 1
  rabbit: 1
  salmon: 3
  sheep: 2
  skeleton: 2
  slime: 2
  spider: 2
  squid: 2
  stray: 2
  tropicalfish: 2
  turtle: 2
  witch: 1
  witherskeleton: 2
  wolf: 2
  zombie: 2
  zombiepigman: 3

other:
  # mob spawner spawning range
  spawner-spawn-range: 8
  # don't reduce spawn eggs if there is same entity already in the spawner (non vanilla behavior)
  do-not-waste-spawn-eggs: false
  # give xp drops straight to player
  use-no-xp-orbs: false
  # do not spawn mobs this near to spawn area
  spawn-no-spawning-area: 25
  # kill entities instead of despawning them
  kill-mobs-on-despawn: false

```
