### ISSUE TITLE
Creepers should flash before exploding when ignited with flint and steel

### ISSUE THREAD

**Issue by Walnit** [Nukkit-coders/MobPlugin#187]
### Info

This is:
- [ X] bug report
- [ ] feature request
- [ ] other

### Your issue / suggestion

Normally, when you ignite a creeper it should flash before exploding. However, when you use flint and steel on a creeper it just immediately explodes without flashing. This should be quite easy to fix as it is just a matter of copying the code from the normal explosion (as it works there) to onInteract part of the script so I would appreciate it if this gets fixed soon.

How to replicate:
1. Spawn a creeper
2. Get a flint and steel
3. Use it on the creeper

### Configuration
Link to debugpaste:
```
N/A
```
Config:
```
# config version, do not edit!
config-version: 11

entities:
  # how often the spawn task should run
  # in ticks, 20 ticks = 1 second
  # use 0 to disable entity spawning
  autospawn-ticks: 200
  # how often the despawn task should run
  # in ticks, 20 ticks = 1 second
  # use 0 to disable entity despawning
  despawn-ticks: 12000
  # do not spawn entities in these worlds
  worlds-spawning-disabled: "exampleworld1, exampleworld2"

# spawning limit settings
# per player, in 100 blocks range
autospawn:
  bat: 1
  blaze: 2
  chicken: 2
  cod: 2
  cow: 2
  creeper: 2
  dolphin: 1
  donkey: 1
  enderman: 1
  ghast: 2
  husk: 2
  horse: 2
  magmacube: 2
  mooshroom: 2
  ocelot: 2
  parrot: 1
  pig: 2
  polarbear: 2
  pufferfish: 1
  rabbit: 1
  salmon: 3
  sheep: 2
  skeleton: 2
  slime: 2
  spider: 2
  squid: 2
  stray: 2
  tropicalfish: 2
  turtle: 2
  witch: 1
  witherskeleton: 2
  wolf: 2
  zombie: 2
  zombiepigman: 3

other:
  # mob spawner spawning range
  spawner-spawn-range: 8
  # don't reduce spawn eggs if there is same entity already in the spawner (non vanilla behavior)
  do-not-waste-spawn-eggs: false
  # give xp drops straight to player
  use-no-xp-orbs: false
  # do not spawn mobs this near to spawn area
  spawn-no-spawning-area: 1
  # kill entities instead of despawning them
  kill-mobs-on-despawn: false
```
