### ISSUE TITLE
Bug On mob sinking (nukkit v 1.16.100)

### ISSUE THREAD

**Issue by Sreeraj-S** [Nukkit-coders/MobPlugin#207]
### Info

This is:
- [X] bug report
- [ ] feature request
- [ ] other

### Your issue
The mobs are spawning normally but when walking it started to sink

### Configuration

Config:
```
# config version, do not edit!
config-version: 13

entities:
  # how often the spawn task should run
  # in ticks, 20 ticks = 1 second
  # use 0 to disable entity spawning
  autospawn-ticks: 200
  # how often the despawn task should run
  # in ticks, 20 ticks = 1 second
  # use 0 to disable entity despawning
  despawn-ticks: 12000
  # do not spawn entities in these worlds
  worlds-spawning-disabled: "LobbyBlue"

# spawning limit settings
# per player, in 100 blocks range
autospawn:
  bat: 0
  blaze: 2
  chicken: 3
  cod: 2
  cow: 4
  creeper: 2
  dolphin: 1
  donkey: 1
  enderman: 1
  ghast: 2
  husk: 2
  horse: 2
  magmacube: 2
  mooshroom: 2
  ocelot: 2
  parrot: 1
  pig: 4
  polarbear: 2
  pufferfish: 1
  rabbit: 1
  salmon: 3
  sheep: 3
  skeleton: 2
  slime: 2
  spider: 2
  squid: 2
  stray: 2
  tropicalfish: 2
  turtle: 2
  witch: 1
  witherskeleton: 2
  wolf: 2
  zombie: 2
  zombiepigman: 3
  fox: 2
  panda: 1
  drowned: 2

other:
  # mob spawner spawning range
  spawner-spawn-range: 8
  # don't reduce spawn eggs if there is same entity already in the spawner (non vanilla behavior)
  do-not-waste-spawn-eggs: false
  # give xp drops straight to player
  use-no-xp-orbs: false
  # do not spawn mobs this near to spawn area
  # set -1 to disable
  spawn-no-spawning-area: -1
  # kill entities instead of despawning them
  kill-mobs-on-despawn: false
  # enable mob spawner blocks
  spawners-enabled: true
  # custom enderman max spawns rule for the end world
  end-enderman-spawning: 10

![](https://cdn.discordapp.com/attachments/766145423094054952/781360248702631936/Screenshot_2020-11-26-08-56-09-908_com.miui.videoplayer.jpg)
![Screenshot_2020-11-26-08-56-09-908_com miui videoplayer](https://user-images.githubusercontent.com/56246216/100305855-fcba5780-2fc7-11eb-94fb-ef3fe7509a79.jpg)

```
