### ISSUE TITLE
Mobs jumping / Creeper moving when it can't

### ISSUE THREAD

**Issue by Darker935** [Nukkit-coders/MobPlugin#274]
### Info

This is:
- [ X ] bug report
- [ ] feature request
- [ ] other

### Your issue / suggestion

- All the mobs are jumping on the  ```minecraft:snow_layer```
- Creeper is not stoping ur movement when it's ready to blow/explode

```yml
config-version: 18

entities:
  # How often the spawn task should run
  # In ticks, 20 ticks = 1 second
  # Use 0 to disable entity spawning
  autospawn-ticks: 200
  # How often the despawn task should run
  # In ticks, 20 ticks = 1 second
  # Use 0 to disable entity despawning
  despawn-ticks: 12000
  # Do not spawn entities in these worlds
  worlds-spawning-disabled: "exampleworld1, exampleworld2"

# Spawning limit settings
# Per player, in 100 blocks range
autospawn:
  bat: 0
  blaze: 0
  chicken: 2
  cod: 4
  cow: 2
  creeper: 2
  dolphin: 2
  donkey: 2
  enderman: 2
  ghast: 2
  husk: 2
  horse: 2
  magmacube: 2
  mooshroom: 2
  ocelot: 2
  parrot: 2
  pig: 2
  polarbear: 2
  pufferfish: 2
  rabbit: 2
  salmon: 4
  sheep: 2
  skeleton: 2
  slime: 2
  spider: 2
  squid: 2
  stray: 2
  tropicalfish: 2
  turtle: 2
  witch: 1
  witherskeleton: 2
  wolf: 2
  zombie: 2
  zombiepigman: 4
  fox: 2
  panda: 2
  drowned: 2
  piglin: 4
  hoglin: 0
  llama: 2
  strider: 2

spawners:
  # Enable mob spawner blocks
  enabled: true
  # Mob spawner spawning range
  spawn-range: 4
  # Minimum amount of mobs spawned at a time
  minimum-spawn-count: 1
  # Maximum amount of mobs spawned at a time
  maximum-spawn-count: 4
  # Minimum spawn delay (ticks)
  minimum-delay: 200
  # Maximum spawn delay (ticks)
  maximum-delay: 5000
  # Maximum amount of mobs near the spawner
  maximum-nearby-entities: 16
  # Player must be this close to spawner for it to spawn mobs
  required-player-range: 16
  # Don't reduce spawn eggs if there is an entity already in the spawner (non-vanilla behavior)
  do-not-waste-spawn-eggs: false

other:
  # Give xp drops straight to player
  use-no-xp-orbs: false
  # Do not spawn mobs this near to spawn area
  # Set -1 to disable
  spawn-no-spawning-area: -1
  # Kill entities instead of despawning them
  # This can have a negative impact on performance due to the drops
  kill-mobs-on-despawn: false
  # Custom enderman max spawns rule for the_end world
  end-enderman-spawning: 10
  # If tamed entity owner attacked or attack entity, it will become angry
  check-tamed-entity-attack: true
  # Let creepers explode blocks
  creeper-explode-blocks: true
  # Do not allow creating snow golems, iron golems and withers in these worlds
  worlds-entity-creation-disabled: "exampleworld1, exampleworld2"
  # Allow players to breed mobs
  allow-breeding: true
  # Show boss bar for wither & ender dragon (work in progress)
  show-boss-bar: true
```
