### ISSUE TITLE
Not responding to food

### ISSUE THREAD

**Issue by leifis80** [Nukkit-coders/MobPlugin#70]
### Issue Description

(Running Nukkit from NukkitX (version info bellow), plugin latest version)
None of the animals will respond to food. 
F.ex cow, no respond to wheat (or bukket). Hold the wheat and the cow walks around totally ignoring as it does not see the wheat.
Same happens to the other animals. I have testet chicken, sheep, cow and pig.

### Steps to Reproduce the Issue

1. I just joins the server and try to breed some animals
2. ...
3. ...

### Nukkit Version and Client Version
From the 'version' command in Nukkit:
This server is running Nukkit 1.0dev 「蘋果(Apple)派(Pie)」 implementing API version 1.0.6 for Minecraft: PE v1.2.13 (protocol version 223)

* Client: iOS

#### Config.yml
```
entities:
  auto-spawn-tick: 300
  worlds-spawn-disabled: "exampleworld"

max-spawns:
  bat: 1
  blaze: 0
  chicken: 1
  cow: 1
  creeper: 0
  enderman: 1
  ghast: 0
  husk: 0
  horse: 1
  mooshroom: 1
  ocelot: 1
  pig: 1
  polarbear: 0
  rabbit: 1
  stray: 0
  sheep: 1
  skeleton: 0
  spider: 1
  wolf: 1
  zombie: 0
```
### Crashdump, Backtrace or Other Files

```
<!--- Copy and paste your backtrace here... -->
```
