### ISSUE TITLE
Animals spawning undergroud

### ISSUE THREAD

**Issue by lucascaro** [Nukkit-coders/MobPlugin#78]
### Issue Description

Was playing with the plugin enabled for a while, (thanks!) and when going to mine in a deep cave I noticed animals were spawning like it was the surface. I've never seen this behavior in normal minecraft.
I saw cows, rabbits, and wolfs.

### Steps to Reproduce the Issue

1. start a new server with mob generation
2. go to a deep cave
3. wait

-> animals spawn undergroud.

### Nukkit Version and Client Version

* Nukkit Version: 1.2.5
* Client: Windows10
00:00:22 [INFO] This server is running Nukkit 1.0dev 「蘋果(Apple)派(Pie)」 implementing API version 1.0.6 for Minecraft: PE v1.4 (protocol version 261)

#### Config.yml
```
entities:
  auto-spawn-tick: 200
  worlds-spawn-disabled: "exampleworld1,exampleworld2"

max-spawns:
  bat: 15
  blaze: 2
  chicken: 20
  cow: 3
  creeper: 5
  enderman: 5
  ghast: 5
  husk: 3
  horse: 2
  mooshroom: 1
  ocelot: 2
  pig: 3
  polarbear: 2
  rabbit: 3
  stray: 1
  sheep: 3
  skeleton: 5
  spider: 4
  wolf: 2
  zombie: 10


```
### Crashdump, Backtrace or Other Files
no crash
